version: '3.8'

services:
  xbot_agent:
    build: .
    container_name: xbot_agent_container
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    command: ["python", "main.py"]
